import: a16bitsysop/travis-build-configs:docker-apt.yml

env:
  - IMAGE_NAME=a16bitsysop/postfix-redis APK=postfix

before_script:
  - APK_VER=$(version.py -e -a $APK)
  - ALP_VER=$(version.py -b)
  - VER=$APK_VER"-alpine"$ALP_VER
  - |
      MY_VER="$(version.py -d $IMAGE_NAME)"
      echo "Alpine Version $VER"
      echo "Docker Version $MY_VER"
      if [ -z $NOW ] && [ -n "$MY_VER" ] && [ "$MY_VER" = "$VER" ]; then travis_terminate 0; fi

script:
  - docker-test.sh || travis_terminate 1
  - docker-build-ind.sh
  - docker-build.sh "$VER" "$ALP_VER" "$APK_VER"
  - |
      [ -n $WEBHOOK ] && curl -X POST "https://hooks.microbadger.com/images/$IMAGE_NAME/$WEBHOOK"
